<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CineForge</AssemblyName>
    <RootNamespace>CineForge.Desktop</RootNamespace>
    <ApplicationIcon>..\..\packaging\assets\CineForge.ico</ApplicationIcon>
    <Version>0.5.0</Version>
    <FileVersion>0.5.0.0</FileVersion>
    <AssemblyTitle>CineForge Desktop</AssemblyTitle>
    <Product>CineForge Desktop</Product>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Fonts\*.ttf" />
    <Resource Include="Assets\orbital-globe.gif" />
    <Content Include="Assets\Fonts\OFL-*.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
